<a href="https://colab.research.google.com/github/msatyasambhav-beep/Python-For-AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
type(a)

numpy.ndarray

In [6]:
a = np.array([1,2,3], dtype = float)
print(a)

[1. 2. 3.]


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
type(b)

numpy.ndarray

In [9]:
len(b)

2

In [11]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
c.ndim
b.ndim

2

In [13]:
#get shape of numpy array
a.shape

(3,)

In [14]:
b.shape

(2, 3)

In [15]:
c.shape

(3, 3)

In [16]:
b.dtype

dtype('int64')

In [17]:
c.dtype

dtype('int64')

Accessing , changing specific eleements rows and columns etc

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
a.ndim

2

In [20]:
a.shape


(2, 7)

In [21]:
#get a specific element
a[0,3]

np.int64(4)

In [22]:
#get a specific column from a numpy arraay
a[:,2]

array([ 3, 10])

In [23]:
a[:,0]

array([1, 8])

In [24]:
a[0,3] = 40

In [25]:
print(a)

[[ 1  2  3 40  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
#Change 5th column in !st row to 50
a[0,4] = 50

In [27]:
a

array([[ 1,  2,  3, 40, 50,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

Zeros/Ones method in NumPy

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.ones((3,3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.full((3,3), 50, dtype='float64')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [34]:
np.random.rand(4,4)

array([[0.09425494, 0.98770215, 0.30141692, 0.77256485],
       [0.00226557, 0.45417488, 0.47289946, 0.68519344],
       [0.8593848 , 0.19853777, 0.66154075, 0.15970495],
       [0.34274804, 0.4132995 , 0.75572332, 0.31744808]])

In [35]:
np.random.randint(-5,0, size=(3,3))

array([[-5, -3, -2],
       [-1, -4, -3],
       [-1, -3, -3]])

In [36]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Practice Question

Question #1

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array 'a'?

In [37]:
a = np.array([[1,2,3,4,5,6],
              [20,30,40,50,60,70],
               [12,12,12,12,12,12],
              [11,21,31,41,51,61],
              [13,24,34,44,54,64]
              ])


In [38]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60, 70],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [43]:
a[:3, -5:]

array([[ 2,  3,  4,  5,  6],
       [30, 40, 50, 60, 70],
       [12, 12, 12, 12, 12]])

Question #2
given a postiive number n grater than 2 create a Numpy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

In [47]:
n = 5

In [49]:
import numpy as np
z = np.zeros((n,n), dtype='int')
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [50]:
#make middle row and column all 1
z[n//2,:] =1
z[:,n//2] =1

print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [51]:
a[5//2,:] =1

In [52]:
a[:,5//2] =1

In [53]:
a

array([[ 1,  2,  1,  4,  5,  6],
       [20, 30,  1, 50, 60, 70],
       [ 1,  1,  1,  1,  1,  1],
       [11, 21,  1, 41, 51, 61],
       [13, 24,  1, 44, 54, 64]])

Arithmetic Operation with Numpy - Maths + stats

In [54]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [57]:
a+2

array([3, 4, 5, 6])

In [58]:
a**3

array([ 1,  8, 27, 64])

In [59]:
a

array([1, 2, 3, 4])

In [60]:
a.min()

np.int64(1)

In [61]:
np.min(a)

np.int64(1)

In [62]:
a.min()

np.int64(1)

In [63]:
a.max()

np.int64(4)

In [64]:
a.mean()

np.float64(2.5)

In [67]:
np.max(a, axis=0)

np.int64(4)